export type GlossaryCategory = "navigation" | "engine" | "communications" | "safety" | "ship_parts" | "ranks" | "weapons" | "manoeuvres";

export interface GlossaryTerm {
  en: string;
  it: string;
  category: GlossaryCategory;
  description?: string;
}

export const categoryConfig: Record<GlossaryCategory, { label: string; icon: string; color: string; bg: string }> = {
  navigation:     { label: "Navigation",     icon: "🧭", color: "text-blue-700",    bg: "bg-blue-50 border-blue-200"    },
  engine:         { label: "Engine Room",    icon: "⚙️", color: "text-orange-700",  bg: "bg-orange-50 border-orange-200" },
  communications: { label: "Communications", icon: "📡", color: "text-green-700",   bg: "bg-green-50 border-green-200"   },
  safety:         { label: "Safety",         icon: "🦺", color: "text-red-700",     bg: "bg-red-50 border-red-200"       },
  ship_parts:     { label: "Ship Parts",     icon: "⚓", color: "text-indigo-700",  bg: "bg-indigo-50 border-indigo-200" },
  ranks:          { label: "Ranks & Roles",  icon: "🎖️", color: "text-purple-700",  bg: "bg-purple-50 border-purple-200" },
  weapons:        { label: "Weapons",        icon: "🎯", color: "text-rose-700",    bg: "bg-rose-50 border-rose-200"     },
  manoeuvres:     { label: "Manoeuvres",     icon: "🚢", color: "text-teal-700",    bg: "bg-teal-50 border-teal-200"     },
};

export const glossaryTerms: GlossaryTerm[] = [

  // ─── NAVIGATION ───────────────────────────────────────────────────────────
  { en: "Heading",          it: "Rotta / Prora",              category: "navigation", description: "La direzione in cui punta la prua della nave, espressa in gradi (0°–360°)." },
  { en: "Bearing",          it: "Rilevamento",                category: "navigation", description: "Angolo tra il Nord e la direzione di un oggetto, misurato in gradi." },
  { en: "Chart",            it: "Carta nautica",              category: "navigation", description: "Mappa marina usata per la navigazione: riporta fondali, pericoli, fari e boe." },
  { en: "GPS",              it: "Sistema di posizionamento globale", category: "navigation", description: "Sistema satellitare statunitense per determinare la posizione esatta in tempo reale." },
  { en: "GNSS",             it: "Sistema globale di navigazione satellitare", category: "navigation", description: "Termine generale per tutti i sistemi satellitari di navigazione (GPS, GLONASS, Galileo)." },
  { en: "Radar",            it: "Radar",                      category: "navigation", description: "Sistema che rileva oggetti usando onde radio riflesse." },
  { en: "Sonar",            it: "Sonar",                      category: "navigation", description: "Sistema che usa onde sonore per rilevare oggetti sott'acqua." },
  { en: "Echo sounder",     it: "Ecoscandaglio",              category: "navigation", description: "Strumento che misura la profondità dell'acqua emettendo impulsi sonori." },
  { en: "ECDIS",            it: "Sistema elettronico di carte nautiche", category: "navigation", description: "Sistema digitale per la visualizzazione e la gestione delle carte di navigazione." },
  { en: "AIS",              it: "Sistema di identificazione automatica", category: "navigation", description: "Sistema che trasmette posizione, velocità e rotta della nave ad altre navi e stazioni." },
  { en: "Nautical mile",    it: "Miglio nautico",             category: "navigation", description: "Unità di distanza marina equivalente a 1852 metri." },
  { en: "Knot",             it: "Nodo",                       category: "navigation", description: "Unità di velocità nautica: 1 miglio nautico percorso in un'ora." },
  { en: "Waypoint",         it: "Punto di rotta",             category: "navigation", description: "Punto intermedio di navigazione definito da coordinate geografiche." },
  { en: "Latitude",         it: "Latitudine",                 category: "navigation", description: "Distanza angolare dall'equatore, misurata da 0° a 90° Nord o Sud." },
  { en: "Longitude",        it: "Longitudine",                category: "navigation", description: "Distanza angolare dal meridiano di Greenwich, da 0° a 180° Est o Ovest." },
  { en: "Compass",          it: "Bussola",                    category: "navigation", description: "Strumento che indica il nord magnetico grazie a un ago magnetizzato." },
  { en: "Gyrocompass",      it: "Girobussola",                category: "navigation", description: "Bussola che indica il nord geografico reale, non influenzata dal campo magnetico." },
  { en: "Dead reckoning",   it: "Navigazione stimata",        category: "navigation", description: "Calcolo della posizione attuale basato su velocità, direzione e tempo trascorso." },
  { en: "Pilot",            it: "Pilota di porto",            category: "navigation", description: "Esperto locale che guida la nave in porti, canali o acque difficili." },
  { en: "Tidal current",    it: "Corrente di marea",          category: "navigation", description: "Spostamento orizzontale dell'acqua marina causato dall'attrazione lunare e solare." },
  { en: "Variation",        it: "Declinazione magnetica",     category: "navigation", description: "Differenza angolare tra il nord geografico e il nord magnetico." },
  { en: "Deviation",        it: "Deviazione della bussola",   category: "navigation", description: "Errore della bussola causato dai campi magnetici della nave stessa." },
  { en: "COG",              it: "Rotta rispetto al fondo (Course Over Ground)", category: "navigation", description: "Direzione effettiva di movimento della nave rispetto al fondo marino." },
  { en: "SOG",              it: "Velocità rispetto al fondo (Speed Over Ground)", category: "navigation", description: "Velocità effettiva della nave rispetto al fondo, tenendo conto di correnti e vento." },
  { en: "CPA",              it: "Punto di massima avvicinamento (Closest Point of Approach)", category: "navigation", description: "Il punto più vicino a cui due navi si avvicineranno se mantengono rotta e velocità." },
  { en: "TCPA",             it: "Tempo al massimo avvicinamento",   category: "navigation", description: "Il tempo che manca al punto di massima avvicinamento tra due navi." },
  { en: "VTS",              it: "Servizio di controllo traffico marittimo (Vessel Traffic Service)", category: "navigation", description: "Servizio che monitora e coordina il traffico navale in porto o aree ad alto traffico." },
  { en: "Position line",    it: "Linea di posizione",         category: "navigation", description: "Linea su cui si trova la nave, ricavata da un rilevamento o osservazione." },
  { en: "Running fix",      it: "Punto stimato in movimento", category: "navigation", description: "Posizione ottenuta traslando una linea di posizione precedente alla linea attuale." },
  { en: "Pilotage",         it: "Pilotaggio costiero",        category: "navigation", description: "Navigazione in acque costiere o portuali guidata da punti di riferimento visibili." },
  { en: "Leeway",           it: "Deriva laterale da vento",   category: "navigation", description: "Deviazione dalla rotta prevista causata dall'azione del vento sulla nave." },
  { en: "Set and drift",    it: "Set e deriva di corrente",   category: "navigation", description: "Direzione (set) e velocità (drift) della corrente marina che influenza la rotta." },
  { en: "Chart datum",      it: "Piano di riferimento carta", category: "navigation", description: "Livello minimo teorico di marea usato come zero di riferimento per le profondità." },
  { en: "Transit",          it: "Allineamento / Transito",    category: "navigation", description: "Due oggetti in linea utilizzati come riferimento visivo per determinare la posizione." },
  { en: "Sector light",     it: "Faro a settori",             category: "navigation", description: "Faro che emette luce di colori diversi in settori angolari diversi per indicare zone sicure o pericolose." },
  { en: "Cardinal marks",   it: "Boe cardinali",              category: "navigation", description: "Boe del sistema IALA che indicano la direzione sicura da seguire rispetto a un pericolo." },
  { en: "Celestial navigation", it: "Navigazione astronomica", category: "navigation", description: "Determinazione della posizione usando corpi celesti (sole, stelle, luna) con il sestante." },
  { en: "Tide",             it: "Marea",                      category: "navigation", description: "Variazione periodica del livello del mare causata dall'attrazione gravitazionale di luna e sole." },
  { en: "Log",              it: "Solcometro / Libro di bordo", category: "navigation", description: "Strumento che misura la velocità e la distanza percorsa, o il registro delle operazioni di bordo." },

  // ─── ENGINE ROOM ──────────────────────────────────────────────────────────
  { en: "Main engine",      it: "Motore principale",          category: "engine", description: "Il motore che aziona il propulsore principale della nave." },
  { en: "Boiler",           it: "Caldaia",                    category: "engine", description: "Impianto che produce vapore per la propulsione o i servizi di bordo." },
  { en: "Generator",        it: "Generatore",                 category: "engine", description: "Macchina che produce energia elettrica per alimentare i sistemi di bordo." },
  { en: "Bilge pump",       it: "Pompa di sentina",           category: "engine", description: "Pompa che rimuove l'acqua accumulata nella sentina (fondo della nave)." },
  { en: "Fuel tank",        it: "Serbatoio carburante",       category: "engine", description: "Contenitore del carburante per i motori principali e ausiliari." },
  { en: "Propeller",        it: "Elica",                      category: "engine", description: "Dispositivo rotante che converte la potenza del motore in spinta propulsiva." },
  { en: "Shaft",            it: "Asse di trasmissione",       category: "engine", description: "Asse meccanico che collega il motore all'elica." },
  { en: "Rudder",           it: "Timone",                     category: "engine", description: "Superficie mobile sotto la poppa che controlla la direzione della nave." },
  { en: "Throttle",         it: "Regolatore di velocità",     category: "engine", description: "Dispositivo che controlla la quantità di carburante e quindi la velocità del motore." },
  { en: "Gearbox",          it: "Cambio / Riduttore",         category: "engine", description: "Trasmette e riduce la potenza del motore per adattarla alla velocità ottimale dell'elica." },
  { en: "Ballast pump",     it: "Pompa delle zavorre",        category: "engine", description: "Pompa che immette o scarica acqua dalle casse di zavorra per regolare stabilità e assetto." },
  { en: "Cooling system",   it: "Sistema di raffreddamento",  category: "engine", description: "Sistema che mantiene i motori a temperatura di esercizio ottimale." },
  { en: "Turbocharger",     it: "Turbocompressore",           category: "engine", description: "Dispositivo che aumenta la potenza del motore comprimendo l'aria di aspirazione." },
  { en: "Heat exchanger",   it: "Scambiatore di calore",      category: "engine", description: "Apparato che trasferisce calore tra due fluidi senza farli mescolare." },
  { en: "Purifier",         it: "Purificatore / Separatore",  category: "engine", description: "Centrifuga che separa acqua e impurità dal combustibile o dall'olio lubrificante." },
  { en: "Air compressor",   it: "Compressore d'aria",         category: "engine", description: "Comprime aria ad alta pressione per avviamento motori e sistemi pneumatici." },
  { en: "Bow thruster",     it: "Propulsore di prua",         category: "engine", description: "Elica trasversale nella prua che permette movimenti laterali senza uso del timone." },
  { en: "Stern thruster",   it: "Propulsore di poppa",        category: "engine", description: "Elica trasversale nella poppa per aumentare la manovrabilità in porto." },
  { en: "Stabilizer",       it: "Stabilizzatore",             category: "engine", description: "Pinna retrattile che riduce il rollio della nave nelle acque mosse." },
  { en: "Ballast tank",     it: "Cassa di zavorra",           category: "engine", description: "Serbatoio riempito di acqua per regolare stabilità, assetto e pescaggio della nave." },
  { en: "Sea water pump",   it: "Pompa di acqua di mare",     category: "engine", description: "Pompa che preleva acqua dal mare per il raffreddamento e altri servizi." },
  { en: "Fuel injection",   it: "Iniezione carburante",       category: "engine", description: "Sistema che inietta carburante atomizzato nei cilindri del motore diesel." },
  { en: "Crankshaft",       it: "Albero a gomiti",            category: "engine", description: "Componente che converte il moto alternativo dei pistoni in moto rotativo." },
  { en: "Piston",           it: "Pistone",                    category: "engine", description: "Componente che si muove alternativamente nel cilindro trasmettendo la forza di combustione." },
  { en: "Exhaust valve",    it: "Valvola di scarico",         category: "engine", description: "Valvola che apre per espellere i gas combusti dal cilindro del motore." },

  // ─── COMMUNICATIONS ───────────────────────────────────────────────────────
  { en: "VHF radio",        it: "Radio VHF",                  category: "communications", description: "Radio per comunicazioni marittime a corto raggio. Il canale 16 è riservato alle emergenze." },
  { en: "Mayday",           it: "Mayday",                     category: "communications", description: "Segnale di soccorso internazionale via radio, ripetuto tre volte in caso di pericolo imminente." },
  { en: "Pan-Pan",          it: "Pan-Pan",                    category: "communications", description: "Segnale di urgenza radio, meno grave del Mayday: segnala una situazione che richiede aiuto." },
  { en: "Sécurité",         it: "Sécurité",                   category: "communications", description: "Segnale radio che precede comunicazioni di sicurezza della navigazione (pericoli, meteo)." },
  { en: "GMDSS",            it: "Sistema mondiale di soccorso e sicurezza", category: "communications", description: "Sistema internazionale di comunicazione satellitare e radio per emergenze in mare." },
  { en: "EPIRB",            it: "Radioboa di emergenza",      category: "communications", description: "Dispositivo che trasmette automaticamente la posizione via satellite in emergenza." },
  { en: "SART",             it: "Transponder di ricerca e soccorso", category: "communications", description: "Dispositivo che si attiva in emergenza e appare sul radar dei mezzi di soccorso." },
  { en: "Channel 16",       it: "Canale 16 VHF",             category: "communications", description: "Canale internazionale per l'ascolto continuo e le comunicazioni di emergenza." },
  { en: "Signal lamp",      it: "Lampada di segnalazione",   category: "communications", description: "Lampada per trasmettere messaggi in codice Morse tra navi in vista ottica." },
  { en: "IFF system",       it: "Sistema di identificazione amico/nemico", category: "communications", description: "Sistema elettronico che identifica se un aereo o una nave è amico o nemico." },
  { en: "Satellite phone",  it: "Telefono satellitare",       category: "communications", description: "Telefono che usa satelliti per comunicazioni globali anche in aree remote." },
  { en: "Morse code",       it: "Codice Morse",               category: "communications", description: "Sistema di comunicazione che codifica lettere e numeri in combinazioni di punti e linee." },
  { en: "DSC",              it: "Chiamata selettiva digitale", category: "communications", description: "Sistema VHF/MF/HF che permette di trasmettere segnali di soccorso in modo automatico." },
  { en: "NAVTEX",           it: "NAVTEX",                     category: "communications", description: "Sistema di ricezione automatica di messaggi di sicurezza marittima e previsioni meteo." },
  { en: "Inmarsat",         it: "Inmarsat",                   category: "communications", description: "Sistema di comunicazione satellitare globale per navi e aerei." },
  { en: "SSB radio",        it: "Radio a banda laterale unica (SSB)", category: "communications", description: "Radio a onde corte con lunga portata, usata per comunicazioni oceaniche." },
  { en: "Bridge team",      it: "Equipaggio di plancia",      category: "communications", description: "Il team di ufficiali che gestisce la navigazione dalla plancia di comando." },
  { en: "Traffic list",     it: "Lista del traffico",         category: "communications", description: "Annuncio radio periodico dei messaggi in attesa per le navi in navigazione." },
  { en: "Port control",     it: "Controllo portuale",         category: "communications", description: "Autorità che gestisce le comunicazioni e i movimenti delle navi in porto." },

  // ─── SAFETY ───────────────────────────────────────────────────────────────
  { en: "Life jacket",      it: "Giubbotto di salvataggio",   category: "safety", description: "Dispositivo indossabile omologato che mantiene una persona a galla in acqua." },
  { en: "Life raft",        it: "Zattera di salvataggio",     category: "safety", description: "Zattera gonfiabile per l'evacuazione di emergenza, con sopravvivenza autonoma." },
  { en: "Lifeboat",         it: "Scialuppa di salvataggio",   category: "safety", description: "Imbarcazione di salvataggio motorizzata, a bordo di ogni nave commerciale e militare." },
  { en: "Rescue boat",      it: "Imbarcazione di soccorso",   category: "safety", description: "Piccola imbarcazione veloce per recuperare persone in acqua." },
  { en: "Muster station",   it: "Punto di raccolta",          category: "safety", description: "Luogo designato dove l'equipaggio si raduna in caso di emergenza prima dell'evacuazione." },
  { en: "Abandon ship",     it: "Abbandonare la nave",        category: "safety", description: "Ordine di evacuare immediatamente la nave in caso di pericolo estremo." },
  { en: "Fire extinguisher", it: "Estintore",                 category: "safety", description: "Dispositivo portatile per spegnere piccoli incendi su bordo." },
  { en: "Fire hose",        it: "Manichetta antincendio",     category: "safety", description: "Tubo flessibile ad alta pressione collegato all'impianto antincendio." },
  { en: "SOLAS",            it: "Convenzione SOLAS",          category: "safety", description: "Trattato internazionale sulla sicurezza della vita in mare (Safety of Life at Sea)." },
  { en: "Immersion suit",   it: "Tuta di sopravvivenza",      category: "safety", description: "Tuta impermeabile e isolante che protegge dall'ipotermia in acque fredde." },
  { en: "Man overboard",    it: "Uomo in mare",               category: "safety", description: "Segnalazione di emergenza quando un membro dell'equipaggio cade in mare." },
  { en: "Damage control",   it: "Controllo dei danni",        category: "safety", description: "Procedure per contenere e riparare danni strutturali: allagamenti, incendi, strutture." },
  { en: "Emergency drill",  it: "Esercitazione di emergenza", category: "safety", description: "Simulazione periodica delle procedure di emergenza per addestrare l'equipaggio." },
  { en: "Fire alarm",       it: "Allarme incendio",           category: "safety", description: "Sistema di rilevamento fumi e calore che avvisa automaticamente dell'incendio." },
  { en: "CO2 system",       it: "Sistema CO2 antincendio",    category: "safety", description: "Sistema fisso che scarica anidride carbonica per spegnere incendi in locali chiusi." },
  { en: "General alarm",    it: "Allarme generale",           category: "safety", description: "Segnale acustico che avverte tutto l'equipaggio di una situazione di emergenza." },
  { en: "Watertight door",  it: "Porta stagna",               category: "safety", description: "Porta resistente all'acqua che chiude un compartimento per impedirne l'allagamento." },
  { en: "Watertight bulkhead", it: "Paratia stagna",          category: "safety", description: "Divisione interna della nave che impedisce la propagazione dell'allagamento." },
  { en: "Breathing apparatus", it: "Autorespiratore",         category: "safety", description: "Apparato che fornisce aria per lavorare in ambienti con fumo o gas tossici." },
  { en: "Safety officer",   it: "Ufficiale di sicurezza",     category: "safety", description: "Responsabile delle procedure di sicurezza e delle esercitazioni a bordo." },

  // ─── SHIP PARTS ───────────────────────────────────────────────────────────
  { en: "Hull",             it: "Scafo",                      category: "ship_parts", description: "La struttura principale del corpo della nave, che la mantiene a galla." },
  { en: "Bow",              it: "Prua",                       category: "ship_parts", description: "La parte anteriore della nave, progettata per fendere le onde." },
  { en: "Stern",            it: "Poppa",                      category: "ship_parts", description: "La parte posteriore della nave, dove si trovano il timone e l'elica." },
  { en: "Port",             it: "Babordo (sinistra)",         category: "ship_parts", description: "Il lato sinistro della nave, guardando verso la prua." },
  { en: "Starboard",        it: "Tribordo (destra)",          category: "ship_parts", description: "Il lato destro della nave, guardando verso la prua." },
  { en: "Bridge",           it: "Plancia di comando",         category: "ship_parts", description: "Il centro di comando e controllo della nave, da cui si governa." },
  { en: "Deck",             it: "Coperta / Ponte",            category: "ship_parts", description: "Piano orizzontale della nave. Il ponte principale è il Main Deck." },
  { en: "Keel",             it: "Chiglia",                    category: "ship_parts", description: "La struttura longitudinale principale alla base dello scafo." },
  { en: "Mast",             it: "Albero",                     category: "ship_parts", description: "Struttura verticale su cui vengono montati radar, antenne e segnali." },
  { en: "Anchor",           it: "Ancora",                     category: "ship_parts", description: "Dispositivo pesante che affonda e si fissa al fondo per mantenere ferma la nave." },
  { en: "Funnel",           it: "Fumaiolo",                   category: "ship_parts", description: "Camino da cui fuoriescono i gas di scarico del motore." },
  { en: "Helipad",          it: "Piazzola elicotteri",        category: "ship_parts", description: "Area a bordo destinata all'atterraggio e decollo degli elicotteri." },
  { en: "Waterline",        it: "Linea di galleggiamento",    category: "ship_parts", description: "La linea dove la superficie esterna dello scafo incontra il pelo dell'acqua." },
  { en: "Draft",            it: "Pescaggio",                  category: "ship_parts", description: "Profondità massima dello scafo immerso nell'acqua, dall'ogiva alla chiglia." },
  { en: "Freeboard",        it: "Bordo libero",               category: "ship_parts", description: "Distanza verticale dalla linea di galleggiamento al bordo del ponte principale." },
  { en: "Mooring lines",    it: "Cavi di ormeggio",           category: "ship_parts", description: "Cavi d'acciaio o sintetici usati per legare la nave a banchina o boe." },
  { en: "Bulkhead",         it: "Paratia",                    category: "ship_parts", description: "Divisione verticale interna della nave che separa i vari compartimenti." },
  { en: "Porthole",         it: "Oblò",                       category: "ship_parts", description: "Finestra circolare in acciaio e vetro rinforzato sul bordo della nave." },
  { en: "Gangway",          it: "Passerella",                 category: "ship_parts", description: "Struttura mobile che collega la nave alla banchina per imbarco e sbarco." },
  { en: "Quarterdeck",      it: "Cassero di poppa",           category: "ship_parts", description: "Zona rialzata sulla poppa, tradizionalmente riservata agli ufficiali." },
  { en: "Forecastle",       it: "Castello di prua",           category: "ship_parts", description: "Zona rialzata sulla prua, spesso usata per le operazioni di ancora." },
  { en: "Hatch",            it: "Boccaporto",                 category: "ship_parts", description: "Apertura nel ponte che consente l'accesso ai ponti inferiori o alle stive." },
  { en: "Capstan",          it: "Argano verticale",           category: "ship_parts", description: "Dispositivo meccanico verticale per salpare le ancore e manovrare i cavi." },
  { en: "Winch",            it: "Verricello",                 category: "ship_parts", description: "Argano orizzontale usato per issare carichi, ormeggiare e rimorchiare." },
  { en: "Bollard",          it: "Bitta",                      category: "ship_parts", description: "Colonna metallica su banchina o nave a cui si assicurano i cavi di ormeggio." },
  { en: "Cleat",            it: "Galloccia",                  category: "ship_parts", description: "Elemento metallico con due bracci su cui si avvolgono i cavi di ormeggio." },
  { en: "Conning tower",    it: "Torre di comando del sottomarino", category: "ship_parts", description: "Struttura del sottomarino che emerge in superficie, sede del periscopio e dei comandi." },
  { en: "Flight deck",      it: "Ponte di volo",              category: "ship_parts", description: "Ponte superiore di una portaerei da cui decollano e atterrano gli aerei." },
  { en: "Island",           it: "Isola della portaerei",      category: "ship_parts", description: "Superstruttura laterale sulla portaerei con plancia di comando e controllo aereo." },
  { en: "Hangar",           it: "Hangar / Aviorimessa",       category: "ship_parts", description: "Locale chiuso sotto il ponte di volo dove vengono ricoverati gli aerei." },
  { en: "Beam",             it: "Larghezza massima / Baglio", category: "ship_parts", description: "Larghezza massima dello scafo, o trave trasversale strutturale." },
  { en: "Bilge",            it: "Sentina",                    category: "ship_parts", description: "La parte più bassa dell'interno dello scafo dove si raccolgono acque di infiltrazione." },
  { en: "Shell plating",    it: "Fasciame dello scafo",       category: "ship_parts", description: "Rivestimento esterno in acciaio che forma la superficie dello scafo." },
  { en: "Arrestor wire",    it: "Cavo di arresto",            category: "ship_parts", description: "Cavo sul ponte di volo che frena gli aerei in atterraggio sulle portaerei." },
  { en: "Catapult",         it: "Catapulta",                  category: "ship_parts", description: "Sistema che accelera gli aerei per il decollo dal ponte di volo di una portaerei." },

  // ─── RANKS & ROLES ────────────────────────────────────────────────────────
  { en: "Admiral",          it: "Ammiraglio",                 category: "ranks", description: "Grado più alto nella marina militare, comanda flotte e grandi unità navali." },
  { en: "Rear Admiral",     it: "Contrammiraglio",            category: "ranks", description: "Grado di ammiraglio di divisione, comanda gruppi navali." },
  { en: "Commodore",        it: "Commodoro",                  category: "ranks", description: "Grado intermedio tra capitano di vascello e contrammiraglio." },
  { en: "Captain",          it: "Comandante / Capitano di vascello", category: "ranks", description: "Il massimo responsabile della nave e dell'equipaggio." },
  { en: "Commander",        it: "Capitano di fregata",        category: "ranks", description: "Ufficiale superiore, spesso vice-comandante di una nave maggiore." },
  { en: "Lieutenant Commander", it: "Capitano di corvetta",   category: "ranks", description: "Grado di ufficiale superiore, comanda unità minori o sezioni specialistiche." },
  { en: "Lieutenant",       it: "Tenente di vascello",        category: "ranks", description: "Ufficiale subalterno con responsabilità di reparto o guardia." },
  { en: "Ensign",           it: "Guardiamarina / Sottotenente", category: "ranks", description: "Il grado più basso degli ufficiali, appena usciti dall'accademia navale." },
  { en: "Midshipman",       it: "Aspirante ufficiale",        category: "ranks", description: "Allievo ufficiale in addestramento pratico a bordo." },
  { en: "Petty Officer",    it: "Sottoufficiale",             category: "ranks", description: "Sottufficiale responsabile di un gruppo o settore dell'equipaggio." },
  { en: "Chief Petty Officer", it: "Maresciallo di bordo",    category: "ranks", description: "Sottufficiale di grado superiore con lunga esperienza operativa." },
  { en: "Seaman",           it: "Marinaio",                   category: "ranks", description: "Il grado base dell'equipaggio di una nave militare." },
  { en: "Helmsman",         it: "Timoniere",                  category: "ranks", description: "Chi manovra il timone e mantiene la rotta impostata." },
  { en: "Boatswain",        it: "Nostromo",                   category: "ranks", description: "Responsabile delle operazioni di coperta, dell'equipaggio e dell'attrezzatura." },
  { en: "Lookout",          it: "Vedetta",                    category: "ranks", description: "Membro dell'equipaggio che osserva e segnala pericoli, navi o oggetti." },
  { en: "Navigator",        it: "Ufficiale di rotta",         category: "ranks", description: "Responsabile della pianificazione e conduzione della navigazione." },
  { en: "Chief Engineer",   it: "Capo Macchine",              category: "ranks", description: "Responsabile di tutti i sistemi meccanici, propulsivi ed elettrici della nave." },
  { en: "First Officer",    it: "Primo Ufficiale",            category: "ranks", description: "Secondo in comando dopo il capitano, responsabile anche della sicurezza." },
  { en: "Officer of the Watch", it: "Ufficiale di guardia",   category: "ranks", description: "Ufficiale responsabile della conduzione della nave durante il suo turno di guardia." },
  { en: "Quartermaster",    it: "Segnalatore / Nostromo di plancia", category: "ranks", description: "Assistente di plancia che gestisce segnali, timone e comunicazioni." },

  // ─── WEAPONS ──────────────────────────────────────────────────────────────
  { en: "Torpedo",          it: "Siluro",                     category: "weapons", description: "Arma subacquea autopropulsa che esplode all'impatto con la nave bersaglio." },
  { en: "Torpedo tube",     it: "Tubo lanciasiluri",          category: "weapons", description: "Tubo da cui vengono lanciati i siluri, su sottomarini e navi di superficie." },
  { en: "Anti-ship missile", it: "Missile antinave",          category: "weapons", description: "Missile guidato progettato per colpire e affondare navi di superficie." },
  { en: "Cruise missile",   it: "Missile da crociera",        category: "weapons", description: "Missile a lungo raggio che vola a bassa quota per colpire obiettivi terrestri o navali." },
  { en: "Anti-aircraft missile", it: "Missile superficie-aria", category: "weapons", description: "Missile lanciato da navi per abbattere aerei, elicotteri e missili nemici." },
  { en: "Naval mine",       it: "Mina navale",                category: "weapons", description: "Ordigno esplosivo posizionato in acqua che esplode per contatto o prossimità." },
  { en: "Depth charge",     it: "Bomba di profondità",        category: "weapons", description: "Ordigno esplosivo lanciato o rilasciato per distruggere sottomarini." },
  { en: "Main gun",         it: "Cannone principale",         category: "weapons", description: "Arma da fuoco principale della nave, montata su una torretta girevole." },
  { en: "Turret",           it: "Torretta",                   category: "weapons", description: "Struttura corazzata girevole che alloggia i cannoni principali della nave." },
  { en: "CIWS",             it: "Sistema d'arma ravvicinato", category: "weapons", description: "Sistema automatico di cannoni gatling per abbattere missili e aerei a corto raggio." },
  { en: "Sonar array",      it: "Schiera sonar",              category: "weapons", description: "Sistema di idrofoni per il rilevamento dei sottomarini, trainato o fisso allo scafo." },
  { en: "Chaff",            it: "Chaff (dipoli radar)",       category: "weapons", description: "Nuvola di strisce metalliche sparata per ingannare i radar dei missili nemici." },
  { en: "Flare",            it: "Bengala / Flare",            category: "weapons", description: "Fonte di calore artificiale sparata per ingannare i missili a guida infrarossa." },
  { en: "Decoy",            it: "Esca / Decoy",               category: "weapons", description: "Dispositivo che imita la firma radar o acustica della nave per attirare i missili nemici." },
  { en: "Combat Management System", it: "Sistema di gestione del combattimento", category: "weapons", description: "Sistema informatico integrato che coordina sensori, armi e comunicazioni in battaglia." },
  { en: "Active sonar",     it: "Sonar attivo",               category: "weapons", description: "Sonar che emette impulsi sonori e rileva l'eco riflesso dagli oggetti sott'acqua." },
  { en: "Passive sonar",    it: "Sonar passivo",              category: "weapons", description: "Sonar che ascolta i rumori prodotti dai sottomarini senza emettere segnali propri." },
  { en: "Anti-submarine warfare", it: "Guerra antisommergibile (ASW)", category: "weapons", description: "Insieme di tecniche e sistemi per rilevare, tracciare e distruggere i sottomarini." },
  { en: "Anti-aircraft warfare", it: "Guerra antiaerea (AAW)", category: "weapons", description: "Sistemi e tattiche per difendere la nave dagli attacchi di aerei e missili." },
  { en: "Smoke generator",  it: "Generatore di nebbia fumogena", category: "weapons", description: "Dispositivo che crea una cortina di fumo per nascondere la nave dalla vista nemica." },

  // ─── MANOEUVRES ───────────────────────────────────────────────────────────
  { en: "Mooring",          it: "Ormeggio",                   category: "manoeuvres", description: "Operazione di ancoraggio o legatura della nave a una banchina o una boa." },
  { en: "Anchoring",        it: "Ancoraggio",                 category: "manoeuvres", description: "Procedura di calare l'ancora per mantenere ferma la nave in rada." },
  { en: "Berthing",         it: "Attracco / Accosto",         category: "manoeuvres", description: "Avvicinamento e accostamento della nave alla banchina." },
  { en: "Undocking",        it: "Disormeggio",                category: "manoeuvres", description: "Manovra di distacco dalla banchina e allontanamento dal porto." },
  { en: "Towing",           it: "Rimorchio",                  category: "manoeuvres", description: "Operazione di trainare una nave in avaria con cavi di rimorchio." },
  { en: "Underway replenishment", it: "Rifornimento in navigazione", category: "manoeuvres", description: "Trasferimento di carburante, munizioni o rifornimenti tra navi mentre sono in movimento." },
  { en: "Convoy",           it: "Convoglio",                  category: "manoeuvres", description: "Gruppo di navi che naviga insieme per protezione reciproca o coordinamento." },
  { en: "Formation",        it: "Formazione navale",          category: "manoeuvres", description: "Disposizione tattica di più navi che navigano in posizioni prefissate." },
  { en: "Man overboard manoeuvre", it: "Manovra uomo in mare", category: "manoeuvres", description: "Manovra di emergenza per tornare rapidamente a recuperare una persona caduta in mare." },
  { en: "Collision avoidance", it: "Manovra di emergenza anticollisione", category: "manoeuvres", description: "Azioni da intraprendere per evitare una collisione con un'altra nave o ostacolo." },
  { en: "Search pattern",   it: "Schema di ricerca",          category: "manoeuvres", description: "Schema di navigazione predefinito adottato dai mezzi di soccorso per la ricerca di superstiti." },
  { en: "Drydock",          it: "Bacino di carenaggio",       category: "manoeuvres", description: "Struttura che viene svuotata d'acqua per permettere la manutenzione dello scafo." },
  { en: "Aground",          it: "Incagliato",                 category: "manoeuvres", description: "Condizione della nave che ha toccato il fondo e non riesce a muoversi." },
  { en: "Overtaking",       it: "Sorpasso in navigazione",    category: "manoeuvres", description: "Manovra regolata dalle COLREG per superare un'altra nave con precedenza." },
  { en: "Sea trial",        it: "Prova in mare",              category: "manoeuvres", description: "Test in mare di una nave nuova o dopo riparazione per verificarne le prestazioni." },
  { en: "Casting off",      it: "Salpare / Mollare gli ormeggi", category: "manoeuvres", description: "Sganciare i cavi di ormeggio per lasciare la banchina." },
  { en: "Heaving to",       it: "Mettersi alla cappa",        category: "manoeuvres", description: "Manovra per ridurre al minimo il movimento della nave in condizioni meteo avverse." },
  { en: "Weighing anchor",  it: "Salpare l'ancora",          category: "manoeuvres", description: "Recuperare l'ancora dal fondo per mettere in navigazione la nave." },
  { en: "Dropping anchor",  it: "Dare fondo",                 category: "manoeuvres", description: "Calare l'ancora per fermare la nave in una posizione prescelta." },
  { en: "Making fast",      it: "Assicurare i cavi",          category: "manoeuvres", description: "Bloccare e assicurare i cavi di ormeggio alla banchina o a una boa." },
  { en: "Stand-by",         it: "In attesa / Pronto",         category: "manoeuvres", description: "Stato di prontezza operativa: motori accesi e pronti a manovrare." },
  { en: "Full ahead",       it: "Avanti tutta",               category: "manoeuvres", description: "Ordine di portare i motori alla massima velocità in avanti." },
  { en: "Full astern",      it: "Indietro tutta",             category: "manoeuvres", description: "Ordine di invertire la spinta dell'elica alla massima potenza per frenare o arretrare." },
  { en: "Helm",             it: "Ruota del timone",           category: "ship_parts", description: "La ruota o la barra con cui il timoniere controlla il timone e la direzione della nave." },
  { en: "Life ring",        it: "Salvagente anulare",         category: "safety", description: "Anello galleggiante lanciato a una persona in mare per tenerla a galla." },
  { en: "Log book",         it: "Giornale di bordo",          category: "navigation", description: "Registro ufficiale che documenta tutti gli eventi, rotte e osservazioni durante la navigazione." },
];
