export const quizzes = {
  base: [
    {
      question: "Come si dice 'grazie' in inglese?",
      options: ["Please", "Thank you", "Hello", "Sorry"],
      correct: 1,
    },
    {
      question: "Quale è il presente semplice di 'to be' (io sono)?",
      options: ["I was", "I am", "I will be", "I have been"],
      correct: 1,
    },
    {
      question: "Come si chiede 'Come stai?' in inglese?",
      options: ["How are you?", "Are you?", "How you are?", "What are you?"],
      correct: 0,
    },
    {
      question: "Quale articolo indeterminativo usiamo prima di 'apple'?",
      options: ["a", "an", "the", "some"],
      correct: 1,
    },
    {
      question: "Qual è il plurale di 'child'?",
      options: ["childs", "children", "childes", "childer"],
      correct: 1,
    },
    {
      question: "Come si dice 'no' in inglese?",
      options: ["Yes", "No", "Not", "Never"],
      correct: 1,
    },
  ],
  intermedio: [
    {
      question: "Completa: 'If I had known, I _____ gone.'",
      options: ["would have", "will have", "have", "would"],
      correct: 0,
    },
    {
      question: "Quale tempo verbale è corretto? 'She ____ live in London for 5 years.'",
      options: ["has lived", "lived", "lives", "is living"],
      correct: 0,
    },
    {
      question: "Quale frase è corretta?",
      options: [
        "Despite of the rain, we went out",
        "Although the rain, we went out",
        "In spite of the rain, we went out",
        "Although of the rain, we went out",
      ],
      correct: 2,
    },
    {
      question: "Cosa significa 'to put up with'?",
      options: ["tollerare", "costruire", "sollevare", "immagazzinare"],
      correct: 0,
    },
    {
      question: "Quale parola è un sinonimo di 'stubborn'?",
      options: ["flexible", "obstinate", "clever", "brave"],
      correct: 1,
    },
    {
      question: "Completa: 'She speaks English _____ fluently than her brother.'",
      options: ["more", "most", "much", "many"],
      correct: 0,
    },
  ],
  business: [
    {
      question: "Come iniziare una email formale in inglese?",
      options: ["Hi there!", "Dear Sir/Madam,", "What's up?", "Ciao,"],
      correct: 1,
    },
    {
      question: "Quale è il termine corretto per 'riunione' in contesto aziendale?",
      options: ["gathering", "meeting", "party", "talk"],
      correct: 1,
    },
    {
      question: "Come si dice 'fatturato' in inglese?",
      options: ["revenue", "profit", "income", "turnover"],
      correct: 0,
    },
    {
      question: "Quale frase è più formale?",
      options: [
        "I want a discount",
        "Could you provide a discount?",
        "Gimme a discount",
        "Discount please",
      ],
      correct: 1,
    },
    {
      question: "Cosa significa 'ROI'?",
      options: [
        "Return on Investment",
        "Rate of Interest",
        "Revenue on Income",
        "Ratio of Information",
      ],
      correct: 0,
    },
    {
      question: "Come terminare una email formale?",
      options: ["See you later!", "Yours sincerely,", "Bye bye!", "Talk soon"],
      correct: 1,
    },
  ],
  marina: [
    {
      question: "Come si dice 'scafo' in inglese navale?",
      options: ["bridge", "hull", "deck", "bow"],
      correct: 1,
    },
    {
      question: "Cosa significa 'conning tower'?",
      options: ["plancia", "torre di comando", "timone", "vela"],
      correct: 1,
    },
    {
      question: "Quale è la prua di una nave?",
      options: ["stern", "bow", "beam", "draft"],
      correct: 1,
    },
    {
      question: "Come si chiama il sistema che frena l'aereo in atterraggio su una portaerei?",
      options: ["catapult", "arrestor wire", "flight deck", "island"],
      correct: 1,
    },
    {
      question: "Cosa sono le 'ballast tanks'?",
      options: [
        "serbatoi di carburante",
        "casse di zavorra",
        "camere di compensazione",
        "tunnel di navigazione",
      ],
      correct: 1,
    },
    {
      question: "Quale è il termine per 'poppa' di una nave?",
      options: ["bow", "stern", "beam", "keel"],
      correct: 1,
    },
  ],

  navigation: [
    { question: "Come si traduce 'heading' in navigazione?", options: ["velocità della nave", "direzione di rotta", "distanza percorsa", "angolo di deriva"], correct: 1 },
    { question: "Cosa indica il termine 'bearing'?", options: ["profondità del fondale", "rilevamento angolare rispetto al nord", "velocità del vento", "temperatura dell'acqua"], correct: 1 },
    { question: "Cosa significa l'acronimo 'GPS'?", options: ["General Patrol System", "Global Positioning System", "Geographic Position Service", "Ground Positioning Satellite"], correct: 1 },
    { question: "Cosa si intende per 'waypoint'?", options: ["una velocità di crociera", "un punto di rotta prestabilito", "un tipo di ancora", "un'onda anomala"], correct: 1 },
    { question: "Come si chiama la carta nautica digitale di bordo?", options: ["AIS", "VHF", "ECDIS", "RADAR"], correct: 2 },
    { question: "Cosa misura il 'draft' di una nave?", options: ["la lunghezza fuori tutto", "il pescaggio, cioè la profondità immersa", "l'altezza dell'albero", "la larghezza massima"], correct: 1 },
    { question: "Cosa indica il 'freeboard'?", options: ["la velocità massima", "il bordo libero, altezza dal galleggiamento al ponte", "il peso del carico", "il numero di eliche"], correct: 1 },
    { question: "A cosa serve il 'gyrocompass'?", options: ["misurare la velocità", "determinare il nord geografico", "rilevare le profondità", "calcolare il carburante"], correct: 1 },
    { question: "Cos'è il 'dead reckoning'?", options: ["navigazione tramite GPS", "stima della posizione basata su rotta e velocità", "misura della profondità", "lettura del barometro"], correct: 1 },
    { question: "Come si chiama la 'velocità' di una nave misurata in nodi?", options: ["speed over ground", "knots per hour", "speed in knots", "nautical speed"], correct: 2 },
    { question: "Cosa misura l'eco-scandaglio ('echo sounder')?", options: ["distanza dalla costa", "profondità del fondale marino", "velocità del vento", "intensità del radar"], correct: 1 },
    { question: "Cos'è l'AIS?", options: ["un tipo di ancore", "sistema automatico di identificazione delle navi", "apparato di comunicazione interna", "sistema di controllo motore"], correct: 1 },
    { question: "Cosa significa 'CPA' in navigazione radar?", options: ["Closest Point of Approach – punto di massima avvicinamento", "Chart Position Alarm", "Course Plot Analysis", "Compass Position Altitude"], correct: 0 },
    { question: "Come si chiamano le boe di segnalazione a sistema IALA?", options: ["cardinal marks", "traffic marks", "speed marks", "depth marks"], correct: 0 },
    { question: "Cosa indica il 'port side' di una nave?", options: ["il lato di tribordo (destra)", "la poppa", "il lato di babordo (sinistra)", "la prua"], correct: 2 },
    { question: "Cosa indica il 'starboard side'?", options: ["lato sinistro della nave", "lato destro della nave (tribordo)", "zona motore", "postazione âncora"], correct: 1 },
    { question: "Cos'è il 'log' in navigazione?", options: ["registro scritto degli eventi", "strumento per misurare la velocità e distanza percorsa", "tipo di ancora", "sistema di sollevamento"], correct: 1 },
    { question: "Cosa significa 'set and drift'?", options: ["velocità e direzione della corrente marina", "alzo e abbassamento della marea", "rotta e velocità imposte dal vento", "prua e poppa"], correct: 0 },
    { question: "Cos'è una 'position line'?", options: ["la linea dell'orizzonte", "una linea su cui si trova la nave ricavata da un rilevamento", "la rotta programmata", "il percorso del sole"], correct: 1 },
    { question: "Cosa significa 'leeway'?", options: ["deviazione laterale causata dal vento", "velocità minima di sicurezza", "distanza dal porto", "errore del compasso"], correct: 0 },
    { question: "Cosa è il 'chart datum'?", options: ["data di emissione della carta nautica", "livello di riferimento per le profondità in carta", "il centro della carta nautica", "la scala della carta"], correct: 1 },
    { question: "Cosa si intende per 'pilotage'?", options: ["pilotaggio aereo", "navigazione costiera guidata da un pilota locale", "manovra di ormeggio", "navigazione astronomica"], correct: 1 },
    { question: "Come si traduce 'rudder'?", options: ["ancora", "chiglia", "timone", "elica"], correct: 2 },
    { question: "Cosa significa 'latitude'?", options: ["distanza est-ovest dal meridiano di Greenwich", "distanza nord-sud dall'equatore", "altitudine della nave", "profondità minima di rotta"], correct: 1 },
    { question: "Cosa misura la 'longitude'?", options: ["distanza nord-sud dall'equatore", "distanza est-ovest dal meridiano 0°", "velocità angolare della terra", "inclinazione della chiglia"], correct: 1 },
    { question: "Cosa indica 'SOG' nel linguaggio navale?", options: ["Speed Over Ground – velocità rispetto al fondo", "Signal On Guard", "Safe Operating Guide", "Ship Operation Guide"], correct: 0 },
    { question: "Cosa indica 'COG'?", options: ["Course Over Ground – rotta rispetto al fondo", "Center Of Gravity", "Code Of Good conduct", "Control Of Generator"], correct: 0 },
    { question: "Come si chiama la misura in miglia nautiche della distanza?", options: ["sea mile", "nautical mile", "ocean mile", "water mile"], correct: 1 },
    { question: "Quanti metri equivale un miglio nautico?", options: ["1000 m", "1609 m", "1852 m", "2000 m"], correct: 2 },
    { question: "Cosa si intende per 'GNSS'?", options: ["sistema radio costiero", "Global Navigation Satellite System, sistema globale di navigazione satellitare", "rete di comunicazione navale", "generatore di navigazione a corto raggio"], correct: 1 },
    { question: "Cosa indica 'VTS' in navigazione portuale?", options: ["Vessel Traffic Service – servizio di controllo traffico marittimo", "Very Tall Ship", "Vessel Test System", "Vertical Tracking Sensor"], correct: 0 },
    { question: "Cosa significa 'TCPA'?", options: ["Time of Closest Point of Approach – tempo al massimo avvicinamento", "Total Course Plot Analysis", "Tide Chart Position Alarm", "Traffic Control Position Alert"], correct: 0 },
    { question: "Cosa è una 'running fix'?", options: ["una riparazione d'emergenza", "posizione ottenuta spostando una linea di posizione precedente", "la rotta corrente del navigatore", "la velocità massima"], correct: 1 },
    { question: "Cosa si intende per 'sector light'?", options: ["luce di poppa", "faro con settori colorati che indicano zone sicure o pericolose", "proiettore di ricerca", "luce interna di plancia"], correct: 1 },
    { question: "Cosa indica 'true north' rispetto a 'magnetic north'?", options: ["è lo stesso identico", "true north è il nord geografico reale, magnetic north è quello della bussola magnetica", "true north è quello della bussola", "magnetic north è più preciso"], correct: 1 },
    { question: "Cosa si intende per 'variation' in navigazione?", options: ["oscillazione della velocità", "differenza angolare tra nord magnetico e nord geografico", "variazione di marea", "cambio di rotta"], correct: 1 },
    { question: "Cosa è la 'deviation' della bussola?", options: ["errore causato dai campi magnetici della nave stessa", "l'angolo del vento", "la differenza di marea", "la velocità angolare"], correct: 0 },
    { question: "Come si traduce 'starboard anchor'?", options: ["ancora di babordo", "ancora di tribordo (destra)", "ancora di riserva", "ancora a patta"], correct: 1 },
    { question: "Cosa indica 'beam' di una nave?", options: ["lunghezza fuori tutto", "larghezza massima dello scafo", "profondità della stiva", "altezza della coperta"], correct: 1 },
    { question: "Cosa è il 'keel'?", options: ["l'ancora", "la chiglia, elemento strutturale inferiore dello scafo", "il fumaiolo", "la prua"], correct: 1 },
    { question: "Cosa si intende per 'tide'?", options: ["la corrente marina costante", "il fenomeno del flusso e riflusso dell'acqua marina causato dalla luna", "il vento costiero", "l'onda anomala"], correct: 1 },
    { question: "Cosa indica 'high water'?", options: ["acqua alta pericolosa", "il momento di massima marea", "livello minimo del mare", "corrente rapida"], correct: 1 },
    { question: "Cosa indica 'low water'?", options: ["acqua bassa, minimo della marea", "corrente lenta", "mare calmo", "acque territoriali"], correct: 0 },
    { question: "Come si traduce 'anchorage'?", options: ["area di manovra", "zona di ancoraggio", "punto di ormeggio fisso", "canale di transito"], correct: 1 },
    { question: "Cosa si intende per 'conning'?", options: ["riparazione dello scafo", "il comando delle manovre di timone dalla plancia", "immagazzinamento delle riserve", "test del motore"], correct: 1 },
    { question: "Cosa significa 'windward'?", options: ["sottovento", "sopravvento (lato da cui spira il vento)", "vento debole", "vento di prua"], correct: 1 },
    { question: "Cosa significa 'leeward'?", options: ["sopravvento", "sottovento (lato opposto al vento)", "vento forte", "zona di tempesta"], correct: 1 },
    { question: "Cosa è il 'helm'?", options: ["il fumaiolo", "la ruota o leva di governo del timone", "il generatore di bordo", "la sirena"], correct: 1 },
    { question: "Cosa indica 'mooring'?", options: ["navigazione d'altura", "ormeggio della nave a banchina o a gavitello", "manovra di ancoraggio", "cambio di rotta"], correct: 1 },
    { question: "Cosa significa 'ETA' in navigazione?", options: ["Estimated Time of Arrival – orario stimato di arrivo", "Emergency Towing Assistance", "Engine Test Alarm", "Exact Track Altitude"], correct: 0 },
  ],

  engine: [
    { question: "Come si traduce 'main engine'?", options: ["motore ausiliario", "motore principale", "generatore elettrico", "pompa di sentina"], correct: 1 },
    { question: "Cosa è la 'bilge pump'?", options: ["pompa carburante", "pompa per svuotare la sentina (fondo nave)", "pompa dell'olio", "pompa dell'acqua dolce"], correct: 1 },
    { question: "Cosa si intende per 'auxiliary engine'?", options: ["motore principale", "motore ausiliario (es. generatore)", "sistema di controllo remoto", "turbocompressore"], correct: 1 },
    { question: "Cosa è il 'propeller shaft'?", options: ["albero di trasmissione dell'elica", "sistema di ventilazione", "asse del timone", "barra del combustibile"], correct: 0 },
    { question: "Cosa è il 'stern tube'?", options: ["tubo di poppa che protegge l'albero dell'elica", "canna fumaria", "condotto dell'aria", "tubo dell'acqua di raffreddamento"], correct: 0 },
    { question: "Cosa si intende per 'bow thruster'?", options: ["ancora di prua", "propulsore laterale di prua per manovre portuali", "sistema di frenatura", "pompa di zavorra"], correct: 1 },
    { question: "Cosa è un 'heat exchanger'?", options: ["sistema di carica batterie", "scambiatore di calore", "generatore di vapore", "compressore d'aria"], correct: 1 },
    { question: "Cosa è il 'turbocharger'?", options: ["tipo di motore elettrico", "turbocompressore che aumenta la potenza del motore", "pompa ad alta pressione", "filtro carburante"], correct: 1 },
    { question: "Cosa è il 'crankshaft'?", options: ["albero a gomiti del motore", "camme di distribuzione", "pistone del cilindro", "testata del motore"], correct: 0 },
    { question: "Cosa è il 'camshaft'?", options: ["albero a gomiti", "albero a camme che controlla le valvole", "pistoni del motore", "carter dell'olio"], correct: 1 },
    { question: "Cosa sono i 'piston rings'?", options: ["bulloni dei pistoni", "anelli del pistone che garantiscono la tenuta nel cilindro", "coperchi dei cilindri", "valvole di aspirazione"], correct: 1 },
    { question: "Come si traduce 'cylinder head'?", options: ["corpo cilindro", "testata del cilindro", "pistone superiore", "valvola di scarico"], correct: 1 },
    { question: "Cosa è il 'fuel injection'?", options: ["sistema di filtraggio aria", "iniezione del carburante nel cilindro", "sistema di raffreddamento", "lubrificazione dell'albero"], correct: 1 },
    { question: "Cosa è un 'air compressor' in sala macchine?", options: ["ventilatore di raffreddamento", "compressore d'aria per avviamento del motore e altri usi", "pompa del vuoto", "sistema di scarico fumi"], correct: 1 },
    { question: "Cosa è la 'fresh water generator'?", options: ["impianto di ventilazione", "distillatore che produce acqua dolce dal mare", "pompa dell'acqua potabile", "serbatoio dell'acqua dolce"], correct: 1 },
    { question: "Cosa è il 'fuel oil purifier'?", options: ["filtro aria", "centrifuga che separa impurità dall'olio combustibile", "pompa carburante", "valvola di non ritorno"], correct: 1 },
    { question: "Cosa si intende per 'cooling water system'?", options: ["sistema di riscaldamento", "impianto di raffreddamento del motore con acqua", "sistema di trattamento acque di zavorra", "condensatore a vapore"], correct: 1 },
    { question: "Cosa è il 'lubricating oil system'?", options: ["sistema di zavorra", "impianto di lubrificazione del motore", "sistema di raffreddamento", "circuito del carburante"], correct: 1 },
    { question: "Cosa indica 'RPM'?", options: ["Revolutions Per Minute – giri al minuto", "Rate of Power Management", "Radar Position Monitor", "Reserve Pressure Meter"], correct: 0 },
    { question: "Cosa è il 'crankcase'?", options: ["la testata del motore", "il carter che racchiude l'albero a gomiti e la coppa dell'olio", "il filtro aria", "il collettore di scarico"], correct: 1 },
    { question: "Cosa è un 'sea chest'?", options: ["cassaforte di bordo", "presa a mare che fornisce acqua di mare ai sistemi di bordo", "stiva di prua", "cassone del carburante"], correct: 1 },
    { question: "Cosa è la 'oily water separator'?", options: ["separatore oleoacquoso che tratta le acque di sentina prima dello scarico", "filtro olio del motore", "pompa acque nere", "separatore zavorra"], correct: 0 },
    { question: "Cosa è il 'sewage treatment plant'?", options: ["impianto trattamento acque reflue di bordo", "sistema di trattamento zavorra", "generatore di acqua dolce", "purificatore aria"], correct: 0 },
    { question: "Cosa è l''incinerator' di bordo?", options: ["sistema di raffreddamento", "inceneritore per smaltire i rifiuti di bordo", "generatore di vapore", "filtro combustibile"], correct: 1 },
    { question: "Cosa è il 'ballast pump'?", options: ["pompa carburante", "pompa per il riempimento e svuotamento delle casse di zavorra", "pompa sentina", "pompa antincendio"], correct: 1 },
    { question: "Cosa è la 'steering gear'?", options: ["meccanismo di manovra del timone", "sistema di trasmissione motore", "sistema di controllo del carburante", "meccanismo dell'ancora"], correct: 0 },
    { question: "Cosa è il 'shaft seal'?", options: ["sigillo che impedisce l'ingresso d'acqua attorno all'albero dell'elica", "guarnizione della testata", "tenuta dell'olio del motore", "copertura della presa a mare"], correct: 0 },
    { question: "Come si traduce 'overhaul'?", options: ["avaria", "revisione completa di un macchinario", "avvio a freddo", "test a pieno carico"], correct: 1 },
    { question: "Cosa è la 'fire pump'?", options: ["pompa per il sistema di zavorra", "pompa antincendio alimentata indipendentemente dal motore principale", "pompa di drenaggio", "pompa del carburante"], correct: 1 },
    { question: "Cosa si intende per 'specific fuel oil consumption'?", options: ["consumo totale di carburante per viaggio", "consumo di carburante per unità di potenza prodotta", "riserva minima di carburante", "qualità del combustibile"], correct: 1 },
    { question: "Cosa è un 'diesel generator'?", options: ["motore a vapore ausiliario", "generatore elettrico azionato da motore diesel", "alternatore del motore principale", "batteria di emergenza"], correct: 1 },
    { question: "Cosa indica 'astern'?", options: ["moto avanti del motore", "moto indietro / verso poppa", "fermo motore", "velocità massima"], correct: 1 },
    { question: "Cosa indica 'ahead'?", options: ["verso poppa", "moto avanti", "fermo", "velocità ridotta"], correct: 1 },
    { question: "Cosa è il 'fuel oil transfer pump'?", options: ["pompa per trasferire il carburante tra i vari serbatoi di bordo", "pompa di iniezione diretta", "pompa dell'olio lubrificante", "pompa del refrigerante"], correct: 0 },
    { question: "Cosa è il 'boiler' su alcune navi?", options: ["serbatoio carburante", "caldaia che produce vapore per riscaldamento o propulsione", "generatore elettrico", "impianto di zavorra"], correct: 1 },
    { question: "Come si traduce 'exhaust'?", options: ["aspirazione aria", "gas di scarico del motore", "sistema di ventilazione", "circuito di raffreddamento"], correct: 1 },
    { question: "Cosa si intende per 'engine room telegraph'?", options: ["sistema di comunicazione tra plancia e sala macchine per i comandi di manovra", "telegrafo di bordo per comunicazioni radio", "sistema di allarme incendio sala macchine", "indicatore di pressione motore"], correct: 0 },
    { question: "Cosa è la 'bilge' di una nave?", options: ["ponte principale", "parte più bassa dello scafo dove si raccolgono liquidi", "stiva di poppa", "la chiglia esterna"], correct: 1 },
    { question: "Cosa è l''emergency generator'?", options: ["generatore ausiliario di routine", "generatore di emergenza che si avvia automaticamente in caso di blackout", "generatore a batteria", "generatore del motore principale"], correct: 1 },
    { question: "Cosa è la 'lub oil cooler'?", options: ["radiatore dell'olio lubrificante", "serbatoio dell'olio carburante", "filtro dell'olio lubrificante", "pompa di circolazione olio"], correct: 0 },
    { question: "Cosa è il 'fuel filter'?", options: ["filtro dell'aria", "filtro del carburante che rimuove impurità", "filtro dell'olio lubrificante", "filtro dell'acqua di raffreddamento"], correct: 1 },
    { question: "Cosa è il 'starting air system'?", options: ["sistema di ventilazione sala macchine", "sistema di aria compressa per avviare i motori diesel", "sistema antincendio ad aria", "sistema di aspirazione del motore"], correct: 1 },
    { question: "Come si traduce 'throttle'?", options: ["freno", "acceleratore / comando carburante del motore", "timone", "pompa"], correct: 1 },
    { question: "Cosa è il 'main switchboard'?", options: ["quadro elettrico principale di distribuzione energia", "pannello di controllo motore", "sistema di navigazione", "quadro di comunicazione"], correct: 0 },
    { question: "Cosa è la 'double bottom'?", options: ["doppio scafo laterale", "doppio fondo dello scafo contenente casse di zavorra e carburante", "secondo ponte di coperta", "doppio strato di isolamento"], correct: 1 },
    { question: "Come si traduce 'leak'?", options: ["perdita di fluido / perdita d'acqua", "pressione in eccesso", "vibrazione anomala", "surriscaldamento"], correct: 0 },
    { question: "Cosa è la 'pressure gauge'?", options: ["indicatore di temperatura", "manometro per misurare la pressione di un fluido", "sensore di livello", "misuratore di flusso"], correct: 1 },
    { question: "Cosa è il 'temperature gauge'?", options: ["termometro / indicatore di temperatura", "misuratore di pressione", "indicatore di velocità", "sensore di livello liquido"], correct: 0 },
    { question: "Cosa si intende per 'blackout' in sala macchine?", options: ["guasto totale dell'alimentazione elettrica di bordo", "spegnimento programmato dei motori", "arresto del motore principale", "interruzione delle comunicazioni"], correct: 0 },
    { question: "Come si traduce 'maintenance'?", options: ["avaria", "manutenzione ordinaria e straordinaria dei macchinari", "accensione del motore", "ispezione di sicurezza"], correct: 1 },
  ],

  communications: [
    { question: "Quale canale VHF è internazionalmente riservato alla chiamata di soccorso e sicurezza?", options: ["Canale 6", "Canale 12", "Canale 16", "Canale 70"], correct: 2 },
    { question: "Cosa significa 'GMDSS'?", options: ["Global Marine Distress Safety System", "General Maritime Direction Safety Signal", "Global Maritime Distress and Safety System", "Ground Master Distress Service Signal"], correct: 2 },
    { question: "Cosa significa 'DSC' nelle comunicazioni marittime?", options: ["Digital Sound Communication", "Direct Satellite Channel", "Digital Selective Calling – chiamata digitale selettiva", "Distance Signal Code"], correct: 2 },
    { question: "Come si chiama la segnalazione di soccorso via radio: '___' x3, poi posizione e natura del pericolo?", options: ["PAN PAN", "SECURITE", "MAYDAY", "ROGER"], correct: 2 },
    { question: "Cosa significa 'PAN PAN'?", options: ["segnale di soccorso immediato (vita in pericolo)", "segnale di urgenza (persona o nave in difficoltà non imminente)", "segnale di avviso navigazione", "segnale di fine comunicazione"], correct: 1 },
    { question: "Cosa significa 'SECURITE'?", options: ["segnale di pericolo vita", "segnale di urgenza", "segnale di sicurezza – avviso di pericolo navigazione o meteorologico", "segnale di chiamata ordinaria"], correct: 2 },
    { question: "Cosa è l''EPIRB'?", options: ["Emergency Position-Indicating Radio Beacon – radiofaro di emergenza che trasmette la posizione via satellite", "Radio di plancia di bordo", "Sistema di navigazione satellitare", "Radar anticollisione"], correct: 0 },
    { question: "Cosa è il 'SART'?", options: ["Search And Rescue Transponder – trasponder radar per soccorso", "Sistema radio ad alta frequenza", "Sensore di rilevamento temperatura", "Satellite Anchor Rescue Technology"], correct: 0 },
    { question: "Cosa è il 'NAVTEX'?", options: ["sistema di comunicazione VHF", "sistema automatico di ricezione di avvisi meteo e navigazionali", "servizio di tracciamento satellitare", "sistema di identificazione navale"], correct: 1 },
    { question: "Quale banda frequenza usa la comunicazione VHF marittima?", options: ["2–30 MHz", "156–174 MHz", "100–200 kHz", "300–3000 GHz"], correct: 1 },
    { question: "Cosa si intende per 'MF/HF radio'?", options: ["radio a frequenza media e alta per comunicazioni a lungo raggio", "radio VHF per brevi distanze", "radio interna di bordo", "satellite radio"], correct: 0 },
    { question: "Cosa è Inmarsat?", options: ["sistema radar navale", "rete satellitare internazionale per comunicazioni maritime", "sistema GMDSS a corto raggio", "radio VHF ad alta potenza"], correct: 1 },
    { question: "Come si traduce 'radio watchkeeping'?", options: ["manutenzione della radio", "guardia radio – ascolto continuo sui canali obbligatori", "operatore radio di notte", "test periodico della radio"], correct: 1 },
    { question: "Cosa è il 'radio log'?", options: ["registro di bordo", "giornale radio dove si registrano le comunicazioni effettuate", "batteria di riserva radio", "frequenza di emergenza"], correct: 1 },
    { question: "Cosa significa 'ROGER' nelle comunicazioni radio?", options: ["Non capito, ripetere", "Ricevuto e compreso", "In attesa", "Fine comunicazione"], correct: 1 },
    { question: "Cosa significa 'WILCO'?", options: ["ricevuto ma non compreso", "ricevuto, compreso e mi conformerò", "errore nella trasmissione", "richiesta di ripetizione"], correct: 1 },
    { question: "Cosa significa 'OVER' in radio?", options: ["comunicazione terminata", "fine messaggio, risposta attesa dall'altra stazione", "attendi", "non compreso"], correct: 1 },
    { question: "Cosa significa 'OUT' in radio?", options: ["fine trasmissione, nessuna risposta attesa", "non compreso, ripetere", "in ascolto", "errore nel messaggio"], correct: 0 },
    { question: "Come si dice 'A' nell'alfabeto fonetico NATO?", options: ["Alpha", "Adam", "Able", "Arrow"], correct: 0 },
    { question: "Come si dice 'M' nell'alfabeto fonetico NATO?", options: ["Mike", "Mary", "Mother", "Metro"], correct: 0 },
    { question: "Come si dice 'S' nell'alfabeto fonetico NATO?", options: ["Sugar", "Sierra", "Sam", "Sigma"], correct: 1 },
    { question: "Come si dice 'N' nell'alfabeto fonetico NATO?", options: ["November", "Nancy", "Nero", "North"], correct: 0 },
    { question: "Come si dice 'E' nell'alfabeto fonetico NATO?", options: ["Echo", "Easy", "Edward", "Emma"], correct: 0 },
    { question: "Come si dice 'O' nell'alfabeto fonetico NATO?", options: ["Orange", "Ocean", "Oscar", "Ohio"], correct: 2 },
    { question: "Come si dice 'K' nell'alfabeto fonetico NATO?", options: ["Kilo", "King", "Kelly", "Karl"], correct: 0 },
    { question: "Cosa è il 'bridge-to-bridge communication'?", options: ["comunicazione tra la plancia di una nave e una stazione a terra", "comunicazione tra le plance di due navi vicine su VHF canale 13 o 16", "comunicazione interna di bordo", "chiamata radio d'emergenza"], correct: 1 },
    { question: "Come si inizia una chiamata di soccorso via radio?", options: ["MAYDAY MAYDAY MAYDAY, seguita dal nome della nave e posizione", "SOS, posizione, tipo pericolo", "URGENCY, nome nave, posizione", "SECURITE x3, nome nave, pericolo"], correct: 0 },
    { question: "Cosa è un 'SITREP'?", options: ["rapporto situazione – resoconto della situazione attuale", "tipo di radio portatile", "segnale di emergenza alternativo al MAYDAY", "documento di bordo"], correct: 0 },
    { question: "Cosa significa 'SSB radio'?", options: ["Standard Signal Broadcast", "radio a banda laterale unica (Single SideBand) per HF a lungo raggio", "sistema satellite di backup", "radio interna di bordo"], correct: 1 },
    { question: "Cosa è un 'VHF handheld radio'?", options: ["radio VHF portatile per comunicazioni di sicurezza", "radio fissa da plancia", "sistema satellite portatile", "antenna di bordo"], correct: 0 },
    { question: "Cosa significa 'radio silence'?", options: ["silenzio radio – periodo in cui non si trasmette per ascoltare chiamate di soccorso", "guasto alla radio", "test del silenzio radio periodico", "comunicazione segreta"], correct: 0 },
    { question: "Cosa è la 'traffic list'?", options: ["lista delle navi in porto", "elenco di navi con messaggi in attesa trasmesso dalla stazione radio costiera", "frequenze radio a disposizione", "log delle comunicazioni giornaliere"], correct: 1 },
    { question: "Come si comunica una 'position report' via radio?", options: ["si invia solo via satellite", "si trasmette la posizione, rotta, velocità e altre informazioni a orari prestabiliti", "si comunica solo in porto", "si usa solo la radio HF"], correct: 1 },
    { question: "Cosa è un 'weather broadcast' marittimo?", options: ["previsioni meteo trasmesse da stazioni radio costiere a beneficio delle navi in mare", "report meterologico interno di bordo", "sistema di misurazione del vento", "bollettino per porti"], correct: 0 },
    { question: "Cosa sono i 'navigational warnings'?", options: ["avvisi di navigazione che segnalano pericoli, ostacoli o restrizioni di rotta", "ordini di navigazione della capitaneria", "segnalazioni di navi pericolose", "allarmi di bordo"], correct: 0 },
    { question: "Come si traduce 'distress frequency'?", options: ["frequenza di routine", "frequenza di soccorso internazionale", "frequenza per comunicazioni interne", "frequenza di addestramento"], correct: 1 },
    { question: "Cosa è il 'coast radio station'?", options: ["stazione radar costiera", "stazione radio costiera che fornisce servizi di comunicazione alle navi", "ufficio portuale", "stazione meteo"], correct: 1 },
    { question: "Cosa significa 'MMSI'?", options: ["Maritime Mobile Service Identity – numero identificativo della nave per DSC", "Main Marine Safety Instruction", "Minimum Marine Signal Intensity", "Marine Message Signal Identifier"], correct: 0 },
    { question: "Come si traduce 'acknowledge' in radio?", options: ["ignorare", "ricevuta, confermare la ricezione del messaggio", "ripetere il messaggio", "terminare la comunicazione"], correct: 1 },
    { question: "Cosa significa 'say again'?", options: ["finisci la comunicazione", "ripeti il messaggio o la parola precedente", "ho capito", "aspetta"], correct: 1 },
    { question: "Come si chiama il sistema di allerta su frequenza 406 MHz?", options: ["SART", "EPIRB", "DSC", "VHF"], correct: 1 },
    { question: "Cosa è il 'Inmarsat C'?", options: ["sistema di comunicazione vocale", "sistema di messaggistica dati e telex via satellite", "radio VHF portatile", "sistema radar"], correct: 1 },
    { question: "Cosa si intende per 'phonetic alphabet'?", options: ["codice Morse marittimo", "alfabeto che usa parole standard per ogni lettera per evitare errori radio", "alfabeto semaforico", "codice di bandiere navali"], correct: 1 },
    { question: "Cosa è il 'radio operator'?", options: ["tecnico che ripara le radio", "ufficiale responsabile delle comunicazioni radio di bordo", "operatore del radar", "tecnico dei sistemi di navigazione"], correct: 1 },
    { question: "Come si traduce 'transmit'?", options: ["ricevere", "trasmettere un segnale radio", "ascoltare", "registrare"], correct: 1 },
    { question: "Come si traduce 'receive'?", options: ["trasmettere", "ricevere un segnale radio", "chiamare", "rispondere"], correct: 1 },
    { question: "Cosa è il 'channel 70'?", options: ["canale VHF per chiamate di routine", "canale VHF esclusivamente riservato al DSC (Digital Selective Calling)", "canale radio HF", "canale meteo"], correct: 1 },
    { question: "Come si traduce 'signal flags' nel linguaggio navale?", options: ["luci di navigazione", "bandiere di segnalazione internazionale (Codice Internazionale dei Segnali)", "fari costieri", "fumogeni di emergenza"], correct: 1 },
    { question: "Cosa significa 'stand by' nelle comunicazioni radio?", options: ["termina la comunicazione", "attendi, sto per rispondere o cambiare canale", "non capito", "ripeti"], correct: 1 },
  ],

  safety: [
    { question: "Come si traduce 'lifejacket'?", options: ["salvagente anulare", "giubbotto di salvataggio", "zattera di salvataggio", "tuta di immersione"], correct: 1 },
    { question: "Cosa è un 'lifebuoy'?", options: ["zattera di salvataggio", "salvagente anulare (ciambella di salvataggio)", "giubbotto gonfiabile", "segnale di emergenza"], correct: 1 },
    { question: "Cosa è una 'life raft'?", options: ["scialuppa di salvataggio motorizzata", "zattera di salvataggio pneumatica", "giubbotto di salvataggio", "sistema antincendio"], correct: 1 },
    { question: "Cosa è una 'lifeboat'?", options: ["zattera pneumatica", "scialuppa di salvataggio (imbarcazione di salvataggio motorizzata)", "giubbotto di salvataggio", "segnale di soccorso"], correct: 1 },
    { question: "Cosa è l''immersion suit'?", options: ["tuta da sub", "tuta di immersione che protegge dal freddo in acqua (muta stagna)", "tuta antincendio", "equipaggiamento di ancoraggio"], correct: 1 },
    { question: "Cosa è il 'muster station'?", options: ["postazione radar", "punto di raccolta del personale in caso di emergenza (punto di adunata)", "sala macchine", "plancia di comando"], correct: 1 },
    { question: "Cosa è l''emergency drill'?", options: ["test dei motori", "esercitazione di emergenza (evacuazione, antincendio, uomo a mare)", "manutenzione ordinaria", "prova del generatore"], correct: 1 },
    { question: "Cosa significa 'abandon ship'?", options: ["fermare la nave", "abbandonare la nave – ordine di evacuazione totale della nave", "ancorare la nave", "rallentare i motori"], correct: 1 },
    { question: "Cosa è il 'SOLAS'?", options: ["Safety Of Life At Sea – convenzione internazionale sulla sicurezza in mare", "Sistema di allarme luminoso di sicurezza", "Sistema di orientamento laser a bordo", "Servizio di localizzazione navi"], correct: 0 },
    { question: "Cosa è il 'LSA Code'?", options: ["codice delle luci di navigazione", "Codice internazionale degli apparati di salvataggio della vita (Life-Saving Appliances)", "codice dei segnali radio", "normativa carburante"], correct: 1 },
    { question: "Cosa è il 'FSS Code'?", options: ["codice dei segnali radio", "Codice dei sistemi antincendio e di sicurezza (Fire Safety Systems)", "codice di condotta del personale", "normativa sulla zavorra"], correct: 1 },
    { question: "Cosa è l''ISM Code'?", options: ["Codice per la gestione internazionale della sicurezza delle navi", "sistema di identificazione navi", "normativa internazionale sui segnali", "codice di manutenzione dei motori"], correct: 0 },
    { question: "Cosa è la 'muster list'?", options: ["lista del carico di bordo", "ruolo di appello – elenco dei compiti di ogni membro dell'equipaggio in emergenza", "lista dei passeggeri", "lista delle provviste di bordo"], correct: 1 },
    { question: "Cosa è il 'fire extinguisher'?", options: ["idrante antincendio", "estintore portatile", "coperta antincendio", "rilevatore di fumo"], correct: 1 },
    { question: "Quale tipo di estintore usa CO2?", options: ["estintore a schiuma", "estintore a polvere chimica", "estintore a anidride carbonica (CO2)", "estintore ad acqua"], correct: 2 },
    { question: "Quale estintore è adatto per fuochi di classe B (liquidi infiammabili)?", options: ["estintore ad acqua", "estintore a CO2 o a schiuma", "estintore a polvere solo classe A", "nessuno"], correct: 1 },
    { question: "Cosa è un 'parachute flare'?", options: ["razzi di segnalazione ad alta quota con paracadute", "segnale fumogeno", "segnale acustico di emergenza", "batteria di emergenza"], correct: 0 },
    { question: "Cosa è un 'smoke signal'?", options: ["segnale luminoso", "segnale fumogeno di emergenza visivo usato per farsi localizzare", "segnale acustico", "radiofaro"], correct: 1 },
    { question: "Cosa è il 'rescue boat'?", options: ["scialuppa di salvataggio principale", "imbarcazione di soccorso usata per recuperare persone in mare", "elicottero di salvataggio", "zattera di emergenza"], correct: 1 },
    { question: "Cosa significa 'MOB'?", options: ["Man OverBoard – uomo in mare", "Motor On Board", "Master Of Bridge", "Manual Override Button"], correct: 0 },
    { question: "Cosa si fa in caso di 'man overboard'?", options: ["fermare la nave e abbandonarla", "lanciare un salvagente, segnalare la posizione, avviare la manovra di recupero", "contattare il porto", "attendere l'elicottero"], correct: 1 },
    { question: "Cosa è il 'SCBA'?", options: ["Self-Contained Breathing Apparatus – autorespiratore per interventi in ambienti con fumo o gas", "sistema di comunicazione di emergenza", "sistema di controllo della zavorra", "generatore di sicurezza"], correct: 0 },
    { question: "Cosa è una 'fire door'?", options: ["porta di accesso alla sala macchine", "porta tagliafuoco che impedisce la propagazione dell'incendio", "porta stagna", "porta di uscita di emergenza"], correct: 1 },
    { question: "Cosa è un 'fire damper'?", options: ["serranda tagliafuoco nei condotti di ventilazione", "estintore automatico", "pompa antincendio", "rilevatore di fumo"], correct: 0 },
    { question: "Cosa è lo 'sprinkler system'?", options: ["sistema di lavaggio del ponte", "sistema antincendio automatico a pioggia d'acqua", "impianto di zavorra", "sistema di drenaggio"], correct: 1 },
    { question: "Cosa è il 'bilge alarm'?", options: ["allarme di incendio in sala macchine", "allarme che segnala un alto livello d'acqua nella sentina", "allarme di uomo in mare", "allarme del motore principale"], correct: 1 },
    { question: "Cosa è un 'gas detector'?", options: ["strumento per misurare la velocità del vento", "rilevatore di gas pericolosi (es. idrocarburi, ossigeno, H2S)", "misuratore di temperatura", "sensore di pressione"], correct: 1 },
    { question: "Cosa è il 'damage control'?", options: ["controllo dei danni – procedure per contenere allagamenti e danni strutturali alla nave", "controllo della manutenzione ordinaria", "ispezione dello scafo in porto", "riparazione del motore"], correct: 0 },
    { question: "Cosa è un 'watertight door'?", options: ["porta stagna che impedisce il passaggio dell'acqua tra i compartimenti", "porta di sicurezza dell'armeria", "porta tagliafuoco", "porta di accesso al ponte"], correct: 0 },
    { question: "Cosa è l''emergency lighting'?", options: ["sistema di illuminazione ausiliario che si attiva in caso di blackout", "luci di navigazione", "proiettore di ricerca", "luci di posizione"], correct: 0 },
    { question: "Cosa indica il 'free surface effect'?", options: ["il vento che agisce sulla nave", "riduzione della stabilità causata da liquidi liberi a bordo", "galleggiamento della nave scarica", "effetto del ghiaccio sullo scafo"], correct: 1 },
    { question: "Cosa è la 'stability' di una nave?", options: ["la resistenza allo spostamento laterale e la capacità di ritornare in posizione verticale", "la velocità massima della nave", "la resistenza degli scafi agli urti", "la tenuta dei compartimenti stagni"], correct: 0 },
    { question: "Cosa è l''inclining experiment'?", options: ["test di velocità in acque calme", "prova di stabilità per determinare il centro di gravità della nave", "prova dei motori a pieno regime", "test di resistenza dello scafo"], correct: 1 },
    { question: "Cosa è il 'safety officer'?", options: ["ufficiale responsabile della sicurezza di bordo e delle procedure di emergenza", "ufficiale del porto", "capo meccanico", "ufficiale di rotta"], correct: 0 },
    { question: "Cosa è il 'SMS' (Safety Management System)?", options: ["Sistema di gestione della sicurezza previsto dall'ISM Code", "Sistema di messaggistica di bordo", "sistema di sorveglianza", "sistema di segnalazione meteo"], correct: 0 },
    { question: "Cosa è la 'safety committee'?", options: ["commissione di sicurezza portuale", "comitato di sicurezza di bordo che riunisce periodicamente ufficiali per discutere sicurezza", "organo di ispezione esterna", "comitato di classificazione della nave"], correct: 1 },
    { question: "Cosa è il 'fire hose'?", options: ["tubazione flessibile collegata all'idrante per combattere gli incendi a bordo", "tubo di ventilazione", "condotto dell'impianto sprinkler", "tubo di zavorra"], correct: 0 },
    { question: "Cosa è un 'survival craft'?", options: ["imbarcazione o mezzo per la sopravvivenza in mare (scialuppa o zattera)", "equipaggiamento subacqueo", "accessorio per la navigazione costiera", "sistema di recupero carburante"], correct: 0 },
    { question: "Cosa è la 'flooding'?", options: ["allagamento di un compartimento della nave", "tempesta in mare aperto", "piena di corrente marina", "sistema di riempimento delle casse di zavorra"], correct: 0 },
    { question: "Cosa è il 'emergency generator test'?", options: ["test periodico del generatore di emergenza per verificarne il funzionamento", "controllo del motore principale", "prova della pompa antincendio", "test del sistema di comunicazione"], correct: 0 },
    { question: "Come si traduce 'fire watch'?", options: ["guardia antincendio – sorveglianza in aree a rischio durante lavori pericolosi", "orologio di bordo", "guardia di notte in plancia", "allarme incendio automatico"], correct: 0 },
    { question: "Cosa è un 'hot work permit'?", options: ["permesso di lavoro a caldo – autorizzazione per lavori che producono scintille o calore", "permesso di accesso in sala macchine", "certificato di sicurezza nave", "documento per lavori in spazi confinati"], correct: 0 },
    { question: "Cosa è un 'enclosed space entry permit'?", options: ["permesso di entrata in spazi chiusi a bordo per prevenire asfissia o intossicazione", "permesso di accesso al portellone di prua", "autorizzazione per lavori in sala macchine", "documento per accesso al ponte di coperta"], correct: 0 },
    { question: "Come si traduce 'fire alarm'?", options: ["allarme uomo in mare", "allarme incendio", "allarme generale di abbandono nave", "allarme di bassa pressione motore"], correct: 1 },
    { question: "Cosa è il 'general alarm'?", options: ["allarme specifico per incendio", "allarme generale di emergenza che richiama tutto l'equipaggio ai punti di raccolta", "allarme del motore principale", "sistema di avviso meteo"], correct: 1 },
    { question: "Cosa è il 'abandon ship signal'?", options: ["7 fischi brevi + 1 lungo sulla sirena o campanello di bordo", "3 fischi lunghi", "sirena continua per 30 secondi", "fischio singolo"], correct: 0 },
    { question: "Cosa è il 'foam extinguisher'?", options: ["estintore a CO2", "estintore a schiuma adatto per liquidi infiammabili", "estintore a polvere", "estintore ad acqua nebulizzata"], correct: 1 },
    { question: "Cosa è il 'fire drill'?", options: ["esercitazione antincendio periodica obbligatoria", "test del rilevatore di fumo", "manutenzione degli estintori", "ispezione delle pompe antincendio"], correct: 0 },
    { question: "Cosa è il 'emergency position' in caso di incendio?", options: ["posizione del capitano in plancia", "posizione assegnata a ogni membro dell'equipaggio nel piano di emergenza", "posizione della nave in coordinata", "posizione dell'ancora"], correct: 1 },
    { question: "Cosa è il 'personal locator beacon'?", options: ["radiofaro personale di emergenza che trasmette la posizione via satellite", "dispositivo GPS personale", "ricetrasmettitore radio personale", "lampada di segnalazione personale"], correct: 0 },
  ],

  storia: [
    { question: "In quale anno cadde l'Impero Romano d'Occidente?", options: ["410 d.C.", "476 d.C.", "527 d.C.", "800 d.C."], correct: 1 },
    { question: "Chi fu il primo imperatore romano?", options: ["Giulio Cesare", "Augusto", "Tiberio", "Caligola"], correct: 1 },
    { question: "In che anno Colombo scoprì l'America?", options: ["1490", "1492", "1494", "1500"], correct: 1 },
    { question: "Chi fu Napoleone Bonaparte?", options: ["Re di Francia", "Generale e imperatore francese", "Papa", "Re di Prussia"], correct: 1 },
    { question: "In quale secolo visse Leonardo da Vinci?", options: ["XIV", "XV-XVI", "XVII", "XVIII"], correct: 1 },
    { question: "Quale città antica fu distrutta dall'eruzione del Vesuvio?", options: ["Roma", "Napoli", "Pompei", "Ercolano"], correct: 2 },
    { question: "In quale anno iniziò la Rivoluzione Francese?", options: ["1787", "1789", "1791", "1793"], correct: 1 },
    { question: "Quale faraone egiziano costruì la Grande Piramide di Giza?", options: ["Ramses II", "Khufu", "Tutankhamon", "Amenhotep"], correct: 1 },
    { question: "Qual era la religione principale dell'antico Egitto?", options: ["Politeismo", "Monoteismo", "Ateismo", "Dualismo"], correct: 0 },
    { question: "Quale dio egiziano è raffigurato con testa di ibis?", options: ["Ra", "Thot", "Anubis", "Osiride"], correct: 1 },
    { question: "Il Nilo è lungo circa:", options: ["3.000 km", "4.200 km", "5.000 km", "6.500 km"], correct: 2 },
    { question: "In quale periodo l'Egitto raggiunse il massimo splendore?", options: ["Antico Regno", "Medio Regno", "Nuovo Regno", "Periodo Tolemaico"], correct: 2 },
    { question: "Chi era Nefertiti?", options: ["Regina egiziana", "Sacerdotessa", "Divinità", "Guerriera"], correct: 0 },
    { question: "Quale civiltà costruì il Colosseo?", options: ["Grecia", "Egitto", "Roma", "Persia"], correct: 2 },
    { question: "Quali erano i tre ceti della società romana?", options: ["Nobili, Comuni, Schiavi", "Patrizi, Plebei, Schiavi", "Senatori, Cavalieri, Popolo", "Elite, Mezzani, Bassi"], correct: 1 },
    { question: "Chi fu Alessandro Magno?", options: ["Re persiano", "Re macedone", "Imperatore romano", "Faraone egiziano"], correct: 1 },
    { question: "Quale furono le donne guerriere dei Vichinghi?", options: ["Valchirie", "Amazzoni", "Scaldinghe", "Norvensi"], correct: 0 },
    { question: "Da quale regione provenivano principalmente i Vichinghi?", options: ["Danimarca", "Svezia e Norvegia", "Islanda", "Groenlandia"], correct: 1 },
    { question: "Quale fu il principale dio dei Vichinghi?", options: ["Odino", "Thor", "Loki", "Freya"], correct: 0 },
  ],

  geografia: [
    { question: "Qual è il monte più alto del mondo?", options: ["K2", "Monte Everest", "Kanchenjunga", "Lhotse"], correct: 1 },
    { question: "Quale continente è il più piccolo?", options: ["Europa", "Oceania", "Antartide", "Asia"], correct: 1 },
    { question: "Qual è il fiume più lungo d'Africa?", options: ["Congo", "Zambesi", "Nilo", "Limpopo"], correct: 2 },
    { question: "Quanti oceani ci sono sulla Terra?", options: ["3", "4", "5", "6"], correct: 2 },
    { question: "Quale è la capitale del Giappone?", options: ["Osaka", "Tokyo", "Kyoto", "Yokohama"], correct: 1 },
    { question: "Quale paese è il più grande del mondo per superficie?", options: ["Canada", "Russia", "Stati Uniti", "Cina"], correct: 1 },
  ],

  scienze: [
    { question: "Quale gas è essenziale per la respirazione umana?", options: ["Azoto", "Ossigeno", "Anidride carbonica", "Elio"], correct: 1 },
    { question: "Quante ossa ha un adulto umano?", options: ["186", "206", "226", "246"], correct: 1 },
    { question: "Quale è l'elemento chimico più abbondante nella Terra?", options: ["Ossigeno", "Ferro", "Silicio", "Magnesio"], correct: 0 },
    { question: "Quale è la velocità della luce?", options: ["200.000 km/s", "300.000 km/s", "400.000 km/s", "500.000 km/s"], correct: 1 },
    { question: "In quale parte della cellula si trova il DNA?", options: ["Citoplasma", "Nucleo", "Mitocondri", "Ribosomi"], correct: 1 },
    { question: "Quale è la formula chimico dell'acqua?", options: ["H2O", "H2O2", "HO2", "H3O"], correct: 0 },
  ],

  arte: [
    { question: "Chi dipinse la Gioconda?", options: ["Michelangelo", "Leonardo da Vinci", "Raffaello", "Botticelli"], correct: 1 },
    { question: "Quale movimento artistico iniziò con Picasso?", options: ["Impressionismo", "Cubismo", "Surrealismo", "Espressionismo"], correct: 1 },
    { question: "Chi scolpì il David?", options: ["Leonardo da Vinci", "Donatello", "Michelangelo", "Ghiberti"], correct: 2 },
    { question: "In quale periodo visse Michelangelo?", options: ["XIV-XV", "XV-XVI", "XVI-XVII", "XVII-XVIII"], correct: 1 },
    { question: "Quale museo ospita la Venere di Milo?", options: ["Uffizi", "Louvre", "Vaticani", "Accademia"], correct: 1 },
  ],

  astronomia: [
    { question: "Quanti pianeti ci sono nel sistema solare?", options: ["7", "8", "9", "10"], correct: 1 },
    { question: "Quale è il più grande vulcano del sistema solare?", options: ["Monte Bianco", "Etna", "Olimpo Mons", "Krakatoa"], correct: 2 },
    { question: "Quale è il pianeta più vicino al Sole?", options: ["Venere", "Mercurio", "Marte", "Terra"], correct: 1 },
    { question: "Qual è il pianeta più grande del sistema solare?", options: ["Saturno", "Giove", "Nettuno", "Urano"], correct: 1 },
    { question: "Quale è la stella più vicina al Sole?", options: ["Sirio", "Proxima Centauri", "Alpha Centauri", "Vega"], correct: 1 },
  ],

  matematica: [
    { question: "Quanto fa 15 × 12?", options: ["170", "180", "190", "200"], correct: 1 },
    { question: "Quale è il 30% di 200?", options: ["50", "60", "70", "80"], correct: 1 },
    { question: "Quale è il risultato di 144 ÷ 12?", options: ["10", "12", "14", "16"], correct: 1 },
    { question: "Se il raggio di un cerchio è 5, qual è l'area (approssimativamente)?", options: ["70", "79", "85", "90"], correct: 1 },
    { question: "Quale è la radice quadrata di 144?", options: ["10", "11", "12", "13"], correct: 2 },
  ],
};

export const shipQuestions: Record<string, Array<{ question: string; options: string[]; correct: number }>> = {
  "Aircraft Carrier": [
    { question: "⚓ PORTAEREI — Come si chiama il piano di volo di una portaerei?", options: ["flight deck", "main deck", "war deck", "top deck"], correct: 0 },
    { question: "⚓ PORTAEREI — Cosa fa la 'catapult' su una portaerei?", options: ["frena l'aereo in atterraggio", "accelera gli aerei per il decollo", "abbassa il ponte di volo", "lancia razzi difensivi"], correct: 1 },
    { question: "⚓ PORTAEREI — Cosa è l' 'arrestor wire'?", options: ["cavo che lega la nave all'ancora", "cavo che frena l'aereo in atterraggio sul ponte", "sistema di catapulta elettromagnetica", "cavo del sistema di ormeggio"], correct: 1 },
    { question: "⚓ PORTAEREI — Cosa è l' 'island' di una portaerei?", options: ["la zona di parcheggio degli aerei", "la superstruttura con plancia e controllo aereo", "il hangar sottocoperta", "la prua della nave"], correct: 1 },
    { question: "⚓ PORTAEREI — Quanti aeromobili può trasportare tipicamente una grande portaerei?", options: ["5–10", "15–25", "40–90", "oltre 200"], correct: 2 },
    { question: "⚓ PORTAEREI — Come si dice 'portaerei' in inglese militare?", options: ["battle cruiser", "aircraft carrier", "fleet carrier", "war ship"], correct: 1 },
  ],
  "Destroyer": [
    { question: "🚢 CACCIATORPEDINIERE — Cosa significa l'acronimo ASW?", options: ["Advanced Sea Weapon", "Anti-Submarine Warfare – guerra antisommergibile", "Automated Ship Watch", "Air Surface Warning"], correct: 1 },
    { question: "🚢 CACCIATORPEDINIERE — Cosa significa AAW?", options: ["Automatic Anchor Winch", "Anti-Aircraft Warfare – guerra antiaerea", "Advanced Attack Weapon", "Aerial Assault Wing"], correct: 1 },
    { question: "🚢 CACCIATORPEDINIERE — Cosa è il 'CIC' su un cacciatorpediniere?", options: ["motore principale", "Combat Information Center – centro operativo di combattimento", "sistema di navigazione GPS", "sala medica di bordo"], correct: 1 },
    { question: "🚢 CACCIATORPEDINIERE — Come si traduce 'hull' in italiano?", options: ["prua", "poppa", "scafo", "chiglia"], correct: 2 },
    { question: "🚢 CACCIATORPEDINIERE — Quale è la principale missione del cacciatorpediniere?", options: ["trasporto truppe", "scorta e difesa delle flotte maggiori", "pattugliamento costiero", "posa di mine navali"], correct: 1 },
    { question: "🚢 CACCIATORPEDINIERE — Come si chiama la prua di una nave in inglese?", options: ["stern", "beam", "bow", "keel"], correct: 2 },
  ],
  "Submarine": [
    { question: "🤿 SOTTOMARINO — Cosa sono le 'ballast tanks'?", options: ["serbatoi di carburante", "casse di zavorra per regolare la profondità", "serbatoi d'acqua potabile", "camere di decompressione"], correct: 1 },
    { question: "🤿 SOTTOMARINO — Come si chiama la torre di comando del sottomarino?", options: ["bridge", "control tower", "conning tower", "periscope room"], correct: 2 },
    { question: "🤿 SOTTOMARINO — A cosa servono i 'dive planes'?", options: ["decollo di droni", "controllare la profondità e l'assetto in immersione", "bilanciare il carico di siluri", "orientare i siluri"], correct: 1 },
    { question: "🤿 SOTTOMARINO — Cosa è il 'periscope'?", options: ["sistema radar subacqueo", "strumento ottico per osservare la superficie stando in immersione", "tubo di lancio siluri", "antenna radio subacquea"], correct: 1 },
    { question: "🤿 SOTTOMARINO — Come si chiamano i sottomarini con missili balistici nucleari?", options: ["SSN", "SSBN", "SSGN", "SSK"], correct: 1 },
    { question: "🤿 SOTTOMARINO — Qual è il vantaggio principale di un sottomarino nucleare rispetto a uno convenzionale?", options: ["è più veloce in superficie", "autonomia quasi illimitata senza rifornimento", "ha più siluri a bordo", "può trasportare aerei"], correct: 1 },
  ],
  "Frigate": [
    { question: "⚓ FREGATA — Come si chiama la piattaforma per elicotteri su una fregata?", options: ["flight deck", "helipad", "landing platform", "rotor deck"], correct: 1 },
    { question: "⚓ FREGATA — Come si dice 'plancia di comando' in inglese navale?", options: ["deck", "control room", "bridge", "helm station"], correct: 2 },
    { question: "⚓ FREGATA — Cosa è il 'mast' di una nave da guerra?", options: ["il timone", "il fumaiolo", "l'albero con sensori, radar e antenne", "il cannone principale"], correct: 2 },
    { question: "⚓ FREGATA — Cosa significa 'FREMM' per la Marina Militare Italiana?", options: ["Flotta Rapida Europea Multi-Missione", "Fregata Europea Multi-Missione", "Forza di Reazione Europea Marina Militare", "Fregata Rapida Euronato Multi-Missile"], correct: 1 },
    { question: "⚓ FREGATA — Come si chiama il fumaiolo di una nave in inglese?", options: ["stack", "funnel", "chimney", "exhaust tower"], correct: 1 },
    { question: "⚓ FREGATA — Quante fregate FREMM opera la Marina Militare Italiana?", options: ["4", "6", "8", "10"], correct: 3 },
  ],
  "Corvette": [
    { question: "🔱 CORVETTA — Quale è la principale area operativa di una corvetta?", options: ["oceano aperto", "acque costiere e mari ristretti", "Artico", "grandi profondità"], correct: 1 },
    { question: "🔱 CORVETTA — Come si chiama il cannone principale di una corvetta in inglese?", options: ["main rifle", "primary weapon", "main gun", "battle cannon"], correct: 2 },
    { question: "🔱 CORVETTA — Cosa sono le 'depth charges'?", options: ["siluri a ricerca autonoma", "bombe di profondità per attaccare i sottomarini", "mine galleggianti", "missili superficie-aria"], correct: 1 },
    { question: "🔱 CORVETTA — Come si traduce 'rudder'?", options: ["elica", "ancora", "timone", "chiglia"], correct: 2 },
    { question: "🔱 CORVETTA — Come si chiama l'elica di una nave in inglese?", options: ["turbine", "propeller", "rotor", "drive shaft"], correct: 1 },
    { question: "🔱 CORVETTA — Quale caratteristica principale distingue la corvetta da una fregata?", options: ["ha più missili", "è più piccola e veloce, adatta alla guerra costiera", "è più grande e armata", "ha la propulsione nucleare"], correct: 1 },
  ],
  "Patrol Vessel": [
    { question: "🔭 PATTUGLIATORE — Cosa significa SAR in ambito navale?", options: ["Ship And Rescue", "Search And Rescue – ricerca e soccorso", "Satellite Alert Report", "Surface Attack Response"], correct: 1 },
    { question: "🔭 PATTUGLIATORE — Come si chiama la linea di galleggiamento di una nave?", options: ["freeboard", "waterline", "draft line", "hull line"], correct: 1 },
    { question: "🔭 PATTUGLIATORE — Cosa è il 'draft' di una nave?", options: ["la larghezza massima", "il bordo libero dal pelo dell'acqua", "il pescaggio, profondità immersa dello scafo", "la lunghezza fuori tutto"], correct: 2 },
    { question: "🔭 PATTUGLIATORE — Cosa è il 'freeboard'?", options: ["il peso della nave a pieno carico", "il bordo libero, altezza dallo scafo al pelo dell'acqua", "la riserva di carburante", "lo spazio disponibile in stiva"], correct: 1 },
    { question: "🔭 PATTUGLIATORE — Come si chiamano i cavi di ormeggio in inglese?", options: ["anchor chains", "mooring lines", "tow ropes", "dock cables"], correct: 1 },
    { question: "🔭 PATTUGLIATORE — Cosa è la ZEE (Zona Economica Esclusiva) pattugliata dai pattugliatori?", options: ["zona di 12 miglia nautiche", "zona di 200 miglia nautiche dal limite delle acque territoriali", "tutto il Mediterraneo", "acque internazionali oltre 500 miglia"], correct: 1 },
  ],
};

export const courseData = [
  {
    icon: "🌱",
    title: "Inglese Base (A1–A2)",
    description: "Alfabeto, numeri, saluti, presentazioni, verbi essenziali, articoli, il presente semplice.",
    badge: "8 SETTIMANE",
    details: ["Grammatica di base", "Vocabolario quotidiano", "Conversazione semplice"],
  },
  {
    icon: "📗",
    title: "Inglese Pre-Intermedio (A2–B1)",
    description: "Passato, futuro, condizionale, frasi composte e conversazioni pratiche.",
    badge: "10 SETTIMANE",
    details: ["Tempi verbali", "Listening avanzato", "Scrittura formale base"],
  },
  {
    icon: "📘",
    title: "Inglese Intermedio (B1–B2)",
    description: "Grammatica avanzata, reading comprehension, scrittura formale e conversazione fluente.",
    badge: "12 SETTIMANE",
    details: ["Grammatica avanzata", "Reading comprehension", "Conversazione fluente"],
  },
  {
    icon: "📙",
    title: "Inglese Avanzato (C1–C2)",
    description: "Letteratura, stile accademico, dibattiti, idiomi, pronunce regionali.",
    badge: "14 SETTIMANE",
    details: ["Letteratura e stile", "Dibattiti e argomentazione", "Idiomi e pronunce"],
  },
  {
    icon: "💼",
    title: "Business English",
    description: "Email aziendali, riunioni, presentazioni in inglese, negoziazioni internazionali.",
    badge: "8 SETTIMANE",
    details: [],
  },
  {
    icon: "✈️",
    title: "Inglese per Viaggi",
    description: "Aeroporti, alberghi, ristoranti, emergenze, acquisti e orientamento.",
    badge: "4 SETTIMANE",
    details: [],
  },
  {
    icon: "🎓",
    title: "Preparazione IELTS / Cambridge",
    description: "Simulazioni d'esame, writing task, reading avanzato, speaking test.",
    badge: "12 SETTIMANE",
    details: [],
  },
];

export const shipTypes = [
  {
    icon: "✈️",
    name: "Aircraft Carrier",
    nameIt: "Portaerei",
    components: [
      { en: "Flight deck", it: "Piano di volo." },
      { en: "Catapult", it: "Sistema che accelera gli aerei per il decollo." },
      { en: "Arrestor wire", it: "Cavo che frena l'aereo in atterraggio." },
      { en: "Island", it: "Superstruttura con plancia e controllo aereo." },
    ],
  },
  {
    icon: "🚢",
    name: "Destroyer",
    nameIt: "Cacciatorpediniere",
    components: [
      { en: "Hull", it: "Scafo." },
      { en: "Bow", it: "Prua." },
      { en: "Stern", it: "Poppa." },
      { en: "CIC", it: "Centro operativo di combattimento." },
    ],
  },
  {
    icon: "🤿",
    name: "Submarine",
    nameIt: "Sottomarino",
    components: [
      { en: "Conning tower", it: "Torre di comando." },
      { en: "Ballast tanks", it: "Casse di zavorra." },
      { en: "Periscope", it: "Periscopio." },
      { en: "Dive planes", it: "Timoni di profondità." },
    ],
  },
  {
    icon: "⚓",
    name: "Frigate",
    nameIt: "Fregata",
    components: [
      { en: "Bridge", it: "Plancia di comando." },
      { en: "Mast", it: "Albero con sensori e radar." },
      { en: "Funnel", it: "Fumaiolo." },
      { en: "Helipad", it: "Piazzola elicotteri." },
    ],
  },
  {
    icon: "🔱",
    name: "Corvette",
    nameIt: "Corvetta",
    components: [
      { en: "Main gun", it: "Cannone principale." },
      { en: "Depth charges", it: "Bombe di profondità." },
      { en: "Rudder", it: "Timone." },
      { en: "Propeller", it: "Elica." },
    ],
  },
  {
    icon: "🔭",
    name: "Patrol Vessel",
    nameIt: "Pattugliatore",
    components: [
      { en: "Waterline", it: "Linea di galleggiamento." },
      { en: "Draft", it: "Pescaggio." },
      { en: "Freeboard", it: "Bordo libero." },
      { en: "Mooring lines", it: "Cavi di ormeggio." },
    ],
  },
];

export const teamMembers = [
  {
    avatar: "👩‍🏫",
    name: "Prof.ssa Laura Ferretti",
    role: "DIRETTRICE DIDATTICA",
    bio: "Esperta di insegnamento dell'inglese per adulti e contesti professionali.",
  },
  {
    avatar: "👨‍✈️",
    name: "Cap. Marco Olivieri",
    role: "ESPERTO INGLESE NAVALE",
    bio: "Ex ufficiale della Marina Militare Italiana e referente del curriculum tecnico-navale.",
  },
  {
    avatar: "👩‍💼",
    name: "Dott.ssa Sofia Ricci",
    role: "COORDINATRICE CORSI",
    bio: "Linguista specializzata in inglese per scopi specifici e percorsi business.",
  },
  {
    avatar: "🧑‍💻",
    name: "Ing. Davide Conti",
    role: "RESPONSABILE PIATTAFORMA",
    bio: "Sviluppatore e specialista e-learning per un'esperienza digitale semplice e stabile.",
  },
];
